### ISSUE TITLE
Failure on Ubuntu 14.04 x86

### ISSUE THREAD

**Issue by raould** [rtfeldman/node-elm-test#1]
I am just a clueless user.

> elm@1.5.1 postinstall /usr/local/lib/node_modules/elm-test/node_modules/node-elm-compiler/node_modules/elm
> node lib/install.js

  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-doc pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-make pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-package pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-reactor pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-repl pre-build test failed

/usr/local/bin/elm-test -> /usr/local/lib/node_modules/elm-test/bin/elm-test
elm-test@0.2.0 /usr/local/lib/node_modules/elm-test
├── lodash@3.9.3
├── temp@0.8.1 (rimraf@2.2.8)
└── node-elm-compiler@0.3.0 (elm@1.5.1)

**Comment by rtfeldman** [comment]
This is a problem with https://github.com/kevva/elm-bin - which is a depdendency of `node-elm-test`.

What happens if you just run `npm install elm` - same thing?

**Comment by raould** [comment]
Yes, similar "No binary" for that as well. ("sudo npm install -g elm")

**Comment by rtfeldman** [comment]
Gotcha. Unfortunately I'm not sure how to diagnose that beyond opening an issue on https://github.com/kevva/elm-bin - but I suspect once you get that resolved, `elm-test` should just work...

**Comment by raould** [comment]
So, elm-bin from node would conflict with elm-* from cabal and elm-package install * I am guessing?

**Comment by rtfeldman** [comment]
Quite possibly, although I don't know enough about `elm-bin`'s postinstall checks to tell if that's the problem here.
