### ISSUE TITLE
node-elm-test 0.6.0 is probably broken for Elm 0.15

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-elm-test#12]
@rtfeldman Maybe you've actually been trying it with Elm 0.15, so hopefully I'm wrong about this, but it seems like 0.6.0 will be broken for Elm 0.15:

deadfoxygrandpa/elm-test (lower case) is only published for Elm 0.16-alpha, so Elm 0.15 (currently) requires deadfoxygrandpa/Elm-Test (Title Case).  Also laszlopandy/elm-console/1.0.1 (the highest version that works with Elm 0.15 also has a different API than laszlopandy/elm-console/1.0.2, and elm-test might not work with the 0.15 version.

If 0.6.0 works for existing projects, then `elm-test init` is probably broken for Elm 0.15.

**Comment by rtfeldman** [comment]
@avh4 I assume you're correct, but I need to get 0.15.1 working first before I can circle back to 0.16 again - we're actually blocked on elm-bin being broken right now, so I need to update stuff sooner than anticipated in order to make our CI server happy again. :smile:

**Comment by avh4** [comment]
Okay, this branch https://github.com/rtfeldman/node-elm-test/pull/11 is trying to get CI working again with Elm 0.15.1.  The current problem is the problem with the elm-console API that I mentioned.

**Comment by rtfeldman** [comment]
0.15 is definitely alive and well now...thanks for the help on this!
