### ISSUE TITLE
Make CI run a matrix build of 0.15 and 0.16

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-elm-test#14]

**Comment by rtfeldman** [comment]
After the breaking API changes in elm-test 3.0.0, this no longer seems like a good idea; we'd have to maintain two separate examples, and persist that as time progresses.

I'm okay pinning the version of `node-elm-test` to the current Elm release, so this will be pushed as `node-elm-test 0.16.0` and we'll assume compatibility only with 0.16.0.

**Comment by rtfeldman** [comment]
That said, feel free to reopen if you disagree @avh4 :smile:
