### ISSUE TITLE
How to mock the windows global property

### ISSUE THREAD

**Issue by amitaibu** [rtfeldman/node-elm-test#15]
I'm using `elm-history` which is wrapping `window.location` (e.g. [this](https://github.com/TheSeamau5/elm-history/blob/master/src/Native/History.js#L18)), so when running a test via console we get:

```bash
Successfully compiled ./src/elm/TestRunner.elm
Running tests...
Cannot read property 'pathname' of undefined
[stdin]:11129
				throw error;
				      ^
TypeError: Cannot read property 'pathname' of undefined
    at Object.Elm.Native.History.make ([stdin]:9870:54)
    ...
```

Any experience/ pointers on how to mock this data?

**Comment by amitaibu** [comment]
Seems that elm-history needs `window.location` and `window.history` - it would probably make more sense to simply run it on a headless browser, right?

**Comment by amitaibu** [comment]
Here's the gist with the solution - https://gist.github.com/amitaibu/156236d28adddf1c1f16

The idea is that we invoke the tests, after jsdom has finished mocking the environment.

@rtfeldman Should I add this info to the README, or maybe even always include it?

**Comment by rtfeldman** [comment]
I'd go with README for now...`elm-test` isn't technically coupled to a browser environment, and I don't think we want to introduce that coupling.

This workaround may be temporary after Dead Code Elimination ships (currently slated for 0.17 if memory serves), at which point my understanding is that `elm-history`'s code init code wouldn't come along for the test execution unless a test actually used it (which it presumably wouldn't).

**Comment by amitaibu** [comment]
I went with another solution that uses elm-reactor and casperJs, and it feels like a better approach to me - https://github.com/Gizra/elm-hedley/pull/69/files

So I think maybe to give that approach as an example. Sounds ok?

**Comment by rtfeldman** [comment]
Sounds good! :+1:

**Comment by amitaibu** [comment]
[generator-elmlang](https://github.com/Gizra/generator-elmlang) now scaffolds with the tests running with casper, so I think we can close this.
